### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by chiukin** [zyrant/LSNet#1]
hi, 请问在训练代码那里，验证集是使用训练集还是测试集中的某一个来计算best mae，例如vt821还是？

**Comment by zyrant** [comment]
你好, 感谢你的关注。
1. 我们自己根据数据做了个验证集，我在数据集那边下载链接里给了。
2. 使用vt821其实有些模型能取得更好的效果。

**Comment by zyrant** [comment]
没问题的话，我关了，有问题可以再开。
